# Generated by Django 6.0.5 on 2026-05-29 20:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usecases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("mission_planner", "Mission Planner"),
                            ("sensor_analyst", "Sensor Analyst"),
                            ("map_analyst", "Map Analyst"),
                            ("audio_analyst", "Audio Analyst"),
                            ("thermal_analyst", "Thermal Analyst"),
                            ("operator_assistant", "Operator Assistant"),
                            ("report_writer", "Report Writer"),
                            ("risk_assessor", "Risk Assessor"),
                            ("route_planner", "Route Planner"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "prompt_text",
                    models.TextField(
                        help_text="The actual prompt text with placeholders for dynamic data"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, help_text="System-level instructions for the AI"
                    ),
                ),
                (
                    "input_types",
                    models.JSONField(
                        default=list,
                        help_text="List of input types: thermal_frames, audio_segments, map_data, etc.",
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        default=dict, help_text="Expected structure of AI response"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7, help_text="AI temperature setting (0.0-1.0)"
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        default=1000, help_text="Maximum tokens for AI response"
                    ),
                ),
                (
                    "requires_human_review",
                    models.BooleanField(
                        default=True,
                        help_text="Whether AI output requires human review",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "use_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_prompts",
                        to="usecases.usecasetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Prompt Template",
                "verbose_name_plural": "AI Prompt Templates",
                "ordering": ["use_case", "role", "name"],
            },
        ),
    ]
