# Generated by Django 6.0.5 on 2026-05-29 20:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usecases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("mission_id", models.CharField(max_length=100, unique=True)),
                ("use_case_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("aborted", "Aborted"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("objective", models.TextField()),
                ("terrain_description", models.TextField(blank=True)),
                ("simulation_seed", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "use_case_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template this mission is based on",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="missions",
                        to="usecases.usecasetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MissionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("mission_start", "Mission Start"),
                            ("mission_end", "Mission End"),
                            ("agent_deployed", "Agent Deployed"),
                            ("agent_state_change", "Agent State Change"),
                            ("detection", "Detection"),
                            ("failure", "Failure"),
                            ("telemetry", "Telemetry Update"),
                            ("ai_analysis", "AI Analysis"),
                            ("operator_decision", "Operator Decision"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("source_agent_id", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("event_data", models.JSONField(default=dict)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["mission", "timestamp"],
                        name="missions_mi_mission_394217_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="missions_mi_event_t_bf6ebc_idx"
                    ),
                ],
            },
        ),
    ]
