# Generated by Django 6.0.5 on 2026-05-29 21:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionSimulation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("reset", "Reset"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "speed_multiplier",
                    models.FloatField(
                        default=1.0,
                        help_text="Simulation speed: 1x, 2x, 5x, 10x real-time",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Real-world time when simulation started",
                        null=True,
                    ),
                ),
                (
                    "paused_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Real-world time when simulation was paused",
                        null=True,
                    ),
                ),
                (
                    "accumulated_elapsed_seconds",
                    models.FloatField(
                        default=0.0,
                        help_text="Total simulated mission time accumulated before current run/pause",
                    ),
                ),
                (
                    "random_seed",
                    models.IntegerField(
                        blank=True,
                        help_text="Seed for reproducible simulation randomness",
                        null=True,
                    ),
                ),
                (
                    "scenario_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Scenario-specific configuration and events",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mission",
                    models.OneToOneField(
                        help_text="The mission this simulation is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
