# Generated by Django 6.0.5 on 2026-05-31 13:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0002_missionsimulation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenario_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "use_case",
                    models.CharField(
                        choices=[
                            ("collapsed-building-search", "Collapsed Building Search"),
                            ("cave-rescue", "Cave Rescue"),
                            ("flooded-structure", "Flooded Structure"),
                            ("industrial-inspection", "Industrial Inspection"),
                            (
                                "archaeological-exploration",
                                "Archaeological Exploration",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "digital_twin_site_slug",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "digital_twin_terrain_slug",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("estimated_duration_seconds", models.IntegerField(default=600)),
                (
                    "origin_sector_id",
                    models.CharField(
                        help_text="Starting sector ID from Digital Twin", max_length=100
                    ),
                ),
                ("allow_agent_deployment", models.BooleanField(default=False)),
                ("allow_agent_redirect", models.BooleanField(default=False)),
                ("allow_agent_recall", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mission_scenarios",
                "ordering": ["scenario_id"],
            },
        ),
        migrations.CreateModel(
            name="UserMissionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mission_id", models.CharField(db_index=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mission_time_seconds",
                    models.FloatField(
                        help_text="Mission elapsed time when action was taken"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("deploy-agent", "Deploy new agent"),
                            ("redirect-agent", "Redirect agent to new location"),
                            ("recall-agent", "Recall agent to base"),
                            ("abort-mission", "Abort mission"),
                            ("acknowledge-event", "Acknowledge event"),
                            ("manual-control", "Manual control override"),
                        ],
                        max_length=50,
                    ),
                ),
                ("agent_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "target_sector_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("target_x_m", models.FloatField(blank=True, null=True)),
                ("target_y_m", models.FloatField(blank=True, null=True)),
                ("target_z_m", models.FloatField(blank=True, null=True)),
                ("action_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("executed", "Executed"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "user_mission_actions",
                "ordering": ["mission_id", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_id", models.CharField(max_length=100)),
                ("agent_name", models.CharField(max_length=100)),
                (
                    "agent_role",
                    models.CharField(
                        choices=[
                            ("mapper", "Mapper"),
                            ("detector", "Detector"),
                            ("relay", "Relay"),
                            ("specialist", "Specialist"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "deploy_at_seconds",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sensors",
                    models.JSONField(default=list, help_text="List of sensor types"),
                ),
                ("average_speed_m_per_s", models.FloatField(default=2.0)),
                (
                    "battery_drain_rate_percent_per_second",
                    models.FloatField(default=0.05),
                ),
                (
                    "behavior",
                    models.CharField(
                        choices=[
                            ("patrol", "Patrol waypoints in sequence"),
                            ("static", "Deploy and remain stationary"),
                            (
                                "return-to-base",
                                "Return to origin after completing route",
                            ),
                            ("one-way", "Continue until battery depleted"),
                        ],
                        default="patrol",
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_routes",
                        to="missions.missionscenario",
                    ),
                ),
            ],
            options={
                "db_table": "agent_routes",
                "ordering": ["scenario", "deploy_at_seconds", "agent_id"],
                "unique_together": {("scenario", "agent_id")},
            },
        ),
        migrations.CreateModel(
            name="ScenarioEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_at_seconds",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("sector-explored", "Sector exploration complete"),
                            ("detection-thermal", "Thermal detection"),
                            ("detection-audio", "Audio detection"),
                            ("detection-signal", "Signal detection"),
                            ("failure-battery", "Battery failure"),
                            ("failure-sensor", "Sensor failure"),
                            ("failure-communications", "Communications failure"),
                            ("agent-landed-relay", "Agent becomes relay"),
                            ("agent-sacrificed", "Agent sacrificed"),
                            ("escalation", "Mission escalation"),
                            ("user-prompt", "Prompt user for action"),
                        ],
                        max_length=50,
                    ),
                ),
                ("agent_id", models.CharField(blank=True, max_length=100, null=True)),
                ("sector_id", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("success", "Success"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(
                        default=dict, help_text="Event-specific parameters"
                    ),
                ),
                ("requires_user_action", models.BooleanField(default=False)),
                (
                    "user_action_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("acknowledge", "Acknowledge"),
                            ("deploy-agent", "Deploy new agent"),
                            ("redirect-agent", "Redirect agent"),
                            ("abort-mission", "Abort mission"),
                            ("custom", "Custom action"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="missions.missionscenario",
                    ),
                ),
            ],
            options={
                "db_table": "scenario_events",
                "ordering": ["scenario", "trigger_at_seconds"],
            },
        ),
        migrations.CreateModel(
            name="RouteWaypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_order",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "sector_id",
                    models.CharField(
                        help_text="Sector ID from Digital Twin", max_length=100
                    ),
                ),
                ("override_x_m", models.FloatField(blank=True, null=True)),
                ("override_y_m", models.FloatField(blank=True, null=True)),
                ("override_z_m", models.FloatField(blank=True, null=True)),
                (
                    "pause_duration_seconds",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("explore", "Explore sector"),
                            ("scan", "Detailed scan"),
                            ("deploy-relay", "Become relay node"),
                            ("wait", "Wait for other agents"),
                            ("checkpoint", "Continue immediately"),
                        ],
                        default="explore",
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to="missions.agentroute",
                    ),
                ),
            ],
            options={
                "db_table": "route_waypoints",
                "ordering": ["route", "sequence_order"],
                "unique_together": {("route", "sequence_order")},
            },
        ),
    ]
