# Generated by Django 5.2.14 on 2026-06-01 16:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_missionscenario_usermissionaction_agentroute_and_more'),
        ('usecases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missionsimulation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mission Simulation', 'verbose_name_plural': 'Mission Simulations'},
        ),
        migrations.AlterField(
            model_name='mission',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the mission was completed or aborted', null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the mission was created'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique mission identifier (UUID)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible JSON storage for mission-specific configuration'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_id',
            field=models.CharField(help_text="Unique mission identifier string (e.g., 'mission-alpha-001')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='name',
            field=models.CharField(help_text='Human-readable mission name', max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='objective',
            field=models.TextField(help_text='Mission goal and success criteria'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='simulation_seed',
            field=models.IntegerField(blank=True, help_text='Random seed for deterministic simulation reproducibility', null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text="When the mission was started (status changed to 'active')", null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='planned', help_text='Current mission lifecycle state', max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='terrain_description',
            field=models.TextField(blank=True, help_text="Environment characteristics (e.g., 'collapsed building', 'flooded tunnel')"),
        ),
        migrations.AlterField(
            model_name='mission',
            name='use_case_template',
            field=models.ForeignKey(blank=True, help_text='Template this mission is based on (preferred over use_case_type)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='usecases.usecasetemplate'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='use_case_type',
            field=models.CharField(help_text='Legacy use case type string (use use_case_template instead)', max_length=100),
        ),
        migrations.AlterField(
            model_name='missionevent',
            name='confidence',
            field=models.FloatField(blank=True, help_text='Optional confidence score (0.0-1.0) for uncertain events', null=True),
        ),
        migrations.AlterField(
            model_name='missionevent',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed event explanation'),
        ),
        migrations.AlterField(
            model_name='missionevent',
            name='event_data',
            field=models.JSONField(default=dict, help_text='Event-specific structured data (varies by event_type)'),
        ),
        migrations.AlterField(
            model_name='missionevent',
            name='event_type',
            field=models.CharField(choices=[('mission_start', 'Mission Start'), ('mission_end', 'Mission End'), ('agent_deployed', 'Agent Deployed'), ('agent_state_change', 'Agent State Change'), ('detection', 'Detection'), ('failure', 'Failure'), ('telemetry', 'Telemetry Update'), ('ai_analysis', 'AI Analysis'), ('operator_decision', 'Operator Decision')], help_text='Event category', max_length=50),
        ),
        migrations.AlterField(
            model_name='missionevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique event identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='missionevent',
            name='mission',
            field=models.ForeignKey(help_text='Parent mission this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='missions.mission'),
        ),
        migrations.AlterField(
            model_name='missionevent',
            name='source_agent_id',
            field=models.CharField(blank=True, help_text='Agent ID that generated this event (if applicable)', max_length=100),
        ),
        migrations.AlterField(
            model_name='missionevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the event occurred (real-world time, not mission elapsed time)'),
        ),
        migrations.AlterField(
            model_name='missionevent',
            name='title',
            field=models.CharField(help_text='Short event title for timeline display', max_length=200),
        ),
        migrations.AlterField(
            model_name='missionsimulation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this simulation record was created'),
        ),
        migrations.AlterField(
            model_name='missionsimulation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique simulation identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='missionsimulation',
            name='random_seed',
            field=models.IntegerField(blank=True, help_text='Seed for reproducible simulation randomness (inherited from mission.simulation_seed)', null=True),
        ),
        migrations.AlterField(
            model_name='missionsimulation',
            name='scenario_config',
            field=models.JSONField(blank=True, default=dict, help_text='Scenario-specific configuration and events (use case customization)'),
        ),
        migrations.AlterField(
            model_name='missionsimulation',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('reset', 'Reset')], default='not_started', help_text='Current simulation state', max_length=20),
        ),
        migrations.AlterField(
            model_name='missionsimulation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this simulation record was last modified'),
        ),
        migrations.CreateModel(
            name='ScenarioMediaArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable slug for lookups (e.g., collapsed-thermal-void-heat-signature)', max_length=100, unique=True)),
                ('use_case_slug', models.CharField(db_index=True, help_text='Use case this media belongs to (e.g., collapsed-building-search)', max_length=50)),
                ('mission_id', models.CharField(blank=True, db_index=True, help_text='Optional mission ID if media is mission-specific', max_length=100, null=True)),
                ('site_slug', models.CharField(blank=True, help_text='Optional digital twin site slug', max_length=100, null=True)),
                ('terrain_map_slug', models.CharField(blank=True, help_text='Optional terrain map slug', max_length=100, null=True)),
                ('sector_id', models.CharField(blank=True, db_index=True, help_text='Sector ID where media was captured', max_length=100, null=True)),
                ('waypoint_id', models.CharField(blank=True, help_text='Optional waypoint ID', max_length=100, null=True)),
                ('agent_role', models.CharField(blank=True, help_text='Agent role (e.g., mapper, detector, relay)', max_length=50, null=True)),
                ('agent_id', models.CharField(blank=True, db_index=True, help_text='Specific agent ID (e.g., drone-a)', max_length=50, null=True)),
                ('media_type', models.CharField(choices=[('rgb_image', 'RGB Image'), ('low_light_image', 'Low-Light Image'), ('infrared_image', 'Infrared Image'), ('thermal_image', 'Thermal Image'), ('lidar_preview', 'LiDAR Preview'), ('point_cloud_preview', 'Point Cloud Preview'), ('spectrogram', 'Spectrogram'), ('audio_clip', 'Audio Clip'), ('video_placeholder', 'Video Placeholder')], db_index=True, help_text='Type of media artifact', max_length=30)),
                ('sensor_type', models.CharField(choices=[('rgb_camera', 'RGB Camera'), ('low_light_camera', 'Low-Light Camera'), ('infrared_camera', 'Infrared Camera'), ('thermal_camera', 'Thermal Camera'), ('lidar', 'LiDAR'), ('audio_sensor', 'Audio Sensor'), ('seismic_sensor', 'Seismic Sensor'), ('hydrophone', 'Hydrophone'), ('inspection_camera', 'Inspection Camera')], help_text='Sensor that captured this media', max_length=30)),
                ('file_path', models.CharField(help_text='Relative path to media file (e.g., /media/collapsed-building/thermal-void-heat-signature.png)', max_length=500)),
                ('thumbnail_path', models.CharField(blank=True, help_text='Optional thumbnail path', max_length=500, null=True)),
                ('title', models.CharField(help_text='Human-readable title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what the media shows', null=True)),
                ('mission_time_seconds', models.FloatField(db_index=True, help_text='Mission elapsed time when media was captured', validators=[django.core.validators.MinValueValidator(0)])),
                ('display_after_event', models.CharField(blank=True, help_text='Optional event slug to trigger display', max_length=100, null=True)),
                ('linked_event_type', models.CharField(blank=True, db_index=True, help_text='Event type this media is linked to (e.g., thermal_detection)', max_length=50, null=True)),
                ('confidence', models.FloatField(default=0.75, help_text='Confidence score (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('signal_quality', models.FloatField(blank=True, help_text='Signal quality score (0.0-1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('human_review_required', models.BooleanField(default=False, help_text='Whether this media requires human review')),
                ('lighting_state', models.CharField(blank=True, choices=[('natural', 'Natural Light'), ('low_light', 'Low Light'), ('spotlight', 'Spotlight Active'), ('ir_illuminator', 'IR Illuminator Active'), ('thermal_mode', 'Thermal Mode'), ('complete_darkness', 'Complete Darkness')], help_text='Lighting condition when captured', max_length=30, null=True)),
                ('visibility_condition', models.CharField(blank=True, choices=[('clear', 'Clear'), ('dust', 'Dust/Particulate'), ('smoke', 'Smoke'), ('water', 'Water/Moisture'), ('darkness', 'Darkness'), ('obscured', 'Obscured'), ('degraded', 'Degraded')], help_text='Visibility condition', max_length=30, null=True)),
                ('hazard_tags', models.JSONField(blank=True, default=list, help_text='List of hazard tags (e.g., ["unstable_structure", "sharp_debris"])')),
                ('annotation_tags', models.JSONField(blank=True, default=list, help_text='List of annotation tags (e.g., ["thermal anomaly", "review required"])')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional flexible metadata as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scenario Media Artifact',
                'verbose_name_plural': 'Scenario Media Artifacts',
                'db_table': 'scenario_media_artifact',
                'ordering': ['use_case_slug', 'mission_time_seconds', 'created_at'],
                'indexes': [models.Index(fields=['use_case_slug', 'mission_time_seconds'], name='scenario_me_use_cas_5ac228_idx'), models.Index(fields=['sector_id', 'mission_time_seconds'], name='scenario_me_sector__68db3e_idx'), models.Index(fields=['agent_id', 'mission_time_seconds'], name='scenario_me_agent_i_c65c7d_idx'), models.Index(fields=['linked_event_type', 'mission_time_seconds'], name='scenario_me_linked__1c55ad_idx')],
            },
        ),
    ]
