# Generated by Django 6.0.5 on 2026-05-29 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("drone", "Drone"),
                            ("ground_robot", "Ground Robot"),
                            ("amphibious_robot", "Amphibious Robot"),
                            ("relay_node", "Relay Node"),
                            ("sensor", "Passive Sensor"),
                            ("base_station", "Base Station"),
                            ("ai_analyst", "AI Analyst Service"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("available", "Available"),
                            ("deployed", "Deployed"),
                            ("active", "Active"),
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("intermittent", "Intermittent"),
                            ("failed", "Failed"),
                            ("failed_primary_power", "Failed - Primary Power"),
                            ("landed", "Landed"),
                            ("landed_relay", "Landed as Relay"),
                            ("abandoned", "Abandoned"),
                            ("sacrificed", "Sacrificed"),
                            ("lost", "Lost"),
                            ("unknown", "Unknown"),
                            ("recoverable", "Recoverable"),
                            ("recovered", "Recovered"),
                            ("nfc_readable", "NFC Readable"),
                            ("retired", "Retired"),
                        ],
                        default="available",
                        max_length=50,
                    ),
                ),
                ("specifications", models.JSONField(default=dict)),
                ("battery_level", models.IntegerField(blank=True, null=True)),
                ("location", models.JSONField(blank=True, null=True)),
                (
                    "current_mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agents",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "ordering": ["agent_id"],
            },
        ),
        migrations.CreateModel(
            name="AgentStateChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("previous_state", models.CharField(max_length=50)),
                ("new_state", models.CharField(max_length=50)),
                ("reason", models.TextField()),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("location", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_changes",
                        to="agents.agent",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_state_changes",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
