# Generated by Django 6.0.5 on 2026-05-29 20:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usecases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailureProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "affected_component",
                    models.CharField(
                        choices=[
                            ("battery", "Battery"),
                            ("motor", "Motor"),
                            ("lidar", "LiDAR"),
                            ("camera", "Camera"),
                            ("thermal_sensor", "Thermal Sensor"),
                            ("microphone", "Microphone"),
                            ("radio", "Radio"),
                            ("gps", "GPS"),
                            ("imu", "IMU"),
                            ("slam_system", "SLAM System"),
                            ("storage", "Storage"),
                            ("propulsion", "Propulsion"),
                            ("general", "General System"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("time_based", "Time Based"),
                            ("event_based", "Event Based"),
                            ("sector_based", "Sector Based"),
                            ("battery_threshold", "Battery Threshold"),
                            ("random_seeded", "Random Seeded"),
                            ("operator_triggered", "Operator Triggered"),
                            ("scripted_demo", "Scripted Demo"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "trigger_conditions",
                    models.JSONField(
                        default=dict,
                        help_text="Conditions that cause this failure: time, sector, battery_level, etc.",
                    ),
                ),
                (
                    "effects",
                    models.JSONField(
                        default=dict,
                        help_text="Effects: map_confidence_drop, sensor_noise_multiplier, speed_reduction, etc.",
                    ),
                ),
                (
                    "operator_message",
                    models.TextField(
                        help_text="Message shown to operator when this failure occurs"
                    ),
                ),
                ("is_recoverable", models.BooleanField(default=False)),
                (
                    "recovery_actions",
                    models.JSONField(
                        default=list, help_text="Possible recovery actions"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "use_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_profiles",
                        to="usecases.usecasetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Failure Profile",
                "verbose_name_plural": "Failure Profiles",
                "ordering": ["use_case", "severity", "name"],
            },
        ),
    ]
