# Generated by Django 6.0.5 on 2026-05-29 20:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usecases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpectedOutputTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("3d_map", "3D Map"),
                            ("thermal", "Thermal Analysis"),
                            ("audio", "Audio Analysis"),
                            ("environmental", "Environmental Data"),
                            ("device_scan", "Device Scan Results"),
                            ("relay_map", "Relay Network Map"),
                            ("route_map", "Route Map"),
                            ("ai_analysis", "AI Analysis"),
                            ("report", "Mission Report"),
                            ("detection_list", "Detection List"),
                            ("hazard_map", "Hazard Map"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "confidence_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this output requires confidence scoring",
                    ),
                ),
                (
                    "human_review_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this output requires human review before action",
                    ),
                ),
                (
                    "display_priority",
                    models.IntegerField(
                        default=0,
                        help_text="Display order on dashboard (higher = more important)",
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for UI display",
                        max_length=50,
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        default=dict, help_text="Expected structure of this output type"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "use_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expected_outputs",
                        to="usecases.usecasetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expected Output Template",
                "verbose_name_plural": "Expected Output Templates",
                "ordering": ["use_case", "-display_priority", "name"],
            },
        ),
    ]
