# Generated by Django 6.0.5 on 2026-05-30 16:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalTwinSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("cave", "Cave System"),
                            ("archaeology", "Archaeological Site"),
                            ("industrial", "Industrial Facility"),
                            ("synthetic", "Synthetic Environment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                (
                    "source_name",
                    models.CharField(
                        help_text="Name of the source dataset or survey", max_length=200
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, help_text="URL to source dataset or survey project"
                    ),
                ),
                (
                    "source_license",
                    models.CharField(
                        help_text="License identifier (e.g., CC-BY-SA-4.0, ODbL, proprietary)",
                        max_length=200,
                    ),
                ),
                (
                    "attribution",
                    models.TextField(help_text="Required attribution text"),
                ),
                (
                    "sensitivity_level",
                    models.CharField(
                        choices=[
                            ("public_demo", "Public Demo - Full coordinates"),
                            (
                                "reduced_precision",
                                "Reduced Precision - Approximate location",
                            ),
                            ("restricted", "Restricted - No location data"),
                            ("synthetic_only", "Synthetic Only - Not a real location"),
                        ],
                        default="public_demo",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about data processing or restrictions",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Digital Twin Site",
                "verbose_name_plural": "Digital Twin Sites",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MapArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("survey_file", "Survey Data File"),
                            ("point_cloud", "Point Cloud Reference"),
                            ("mesh", "3D Mesh Reference"),
                            ("image", "Image/Photo"),
                            ("reference_link", "External Reference Link"),
                            ("derived_json", "Derived JSON Data"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        blank=True,
                        help_text="File format (e.g., 'survex', 'therion', 'las', 'ply', 'geojson')",
                        max_length=50,
                    ),
                ),
                (
                    "local_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to file within data/ directory",
                        max_length=500,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, help_text="URL to external resource"),
                ),
                (
                    "source_license",
                    models.CharField(help_text="License identifier", max_length=200),
                ),
                (
                    "attribution",
                    models.TextField(help_text="Required attribution text"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this artifact"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "digital_twin_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="mapping.digitaltwinsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Map Artifact",
                "verbose_name_plural": "Map Artifacts",
                "ordering": ["digital_twin_site", "artifact_type", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TerrainMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                (
                    "coordinate_system",
                    models.CharField(
                        choices=[
                            ("local_mission_3d_grid", "Local Mission 3D Grid"),
                            ("utm", "UTM"),
                            ("wgs84", "WGS84"),
                            ("arbitrary_local", "Arbitrary Local"),
                        ],
                        default="local_mission_3d_grid",
                        max_length=50,
                    ),
                ),
                (
                    "origin_label",
                    models.CharField(
                        help_text="Description of coordinate system origin (e.g., 'Cave entrance')",
                        max_length=200,
                    ),
                ),
                (
                    "units",
                    models.CharField(
                        default="meters",
                        help_text="Units for coordinates (typically meters)",
                        max_length=20,
                    ),
                ),
                (
                    "source_format",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("therion", "Therion Survey"),
                            ("survex", "Survex Survey"),
                            ("point_cloud", "Point Cloud Processed"),
                            ("geojson", "GeoJSON"),
                            ("synthetic", "Synthetically Generated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "digital_twin_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terrain_maps",
                        to="mapping.digitaltwinsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terrain Map",
                "verbose_name_plural": "Terrain Maps",
                "ordering": ["digital_twin_site", "name"],
                "unique_together": {("digital_twin_site", "slug")},
            },
        ),
        migrations.CreateModel(
            name="TerrainSector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sector_id",
                    models.CharField(
                        help_text="Sector identifier (e.g., 'C1', 'P3', 'junction-alpha')",
                        max_length=50,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "sector_type",
                    models.CharField(
                        choices=[
                            ("chamber", "Chamber"),
                            ("passage", "Passage"),
                            ("junction", "Junction"),
                            ("entrance", "Entrance"),
                            ("shaft", "Vertical Shaft"),
                            ("sump", "Water-filled Sump"),
                            ("room", "Room"),
                            ("corridor", "Corridor"),
                            ("void", "Void Space"),
                            ("hazard", "Hazard Zone"),
                        ],
                        max_length=50,
                    ),
                ),
                ("x_m", models.FloatField(help_text="X coordinate in meters")),
                ("y_m", models.FloatField(help_text="Y coordinate in meters")),
                (
                    "z_m",
                    models.FloatField(help_text="Z coordinate in meters (vertical)"),
                ),
                (
                    "width_m",
                    models.FloatField(
                        blank=True, help_text="Approximate width in meters", null=True
                    ),
                ),
                (
                    "height_m",
                    models.FloatField(
                        blank=True, help_text="Approximate height in meters", null=True
                    ),
                ),
                (
                    "depth_m",
                    models.FloatField(
                        blank=True, help_text="Approximate depth in meters", null=True
                    ),
                ),
                (
                    "elevation_m",
                    models.FloatField(
                        blank=True,
                        help_text="Elevation relative to reference point",
                        null=True,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0, help_text="Data confidence (0.0-1.0)"
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        help_text="Reference to source data (survey station, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata (dimensions, features, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "terrain_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="mapping.terrainmap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terrain Sector",
                "verbose_name_plural": "Terrain Sectors",
                "ordering": ["terrain_map", "sector_id"],
                "unique_together": {("terrain_map", "sector_id")},
            },
        ),
        migrations.CreateModel(
            name="TerrainPath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("distance_m", models.FloatField(help_text="Path distance in meters")),
                (
                    "bearing_deg",
                    models.FloatField(
                        blank=True,
                        help_text="Compass bearing in degrees (0-360)",
                        null=True,
                    ),
                ),
                (
                    "vertical_change_m",
                    models.FloatField(
                        help_text="Vertical change in meters (positive=up, negative=down)"
                    ),
                ),
                (
                    "path_type",
                    models.CharField(
                        choices=[
                            ("passage", "Passage"),
                            ("climb", "Climb"),
                            ("descent", "Descent"),
                            ("crawl", "Crawl"),
                            ("squeeze", "Tight Squeeze"),
                            ("swim", "Underwater"),
                            ("dive", "Technical Dive"),
                            ("traverse", "Traverse"),
                            ("ladder", "Ladder/Fixed Aid"),
                            ("open", "Open Path"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "traversal_risk",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("moderate", "Moderate Risk"),
                            ("high", "High Risk"),
                            ("extreme", "Extreme Risk"),
                            ("impassable", "Impassable"),
                        ],
                        default="low",
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0, help_text="Data confidence (0.0-1.0)"
                    ),
                ),
                (
                    "capabilities_required",
                    models.JSONField(
                        default=list,
                        help_text="Required capabilities (e.g., ['waterproof', 'vertical_mobility'])",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata (restrictions, hazards, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "terrain_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths",
                        to="mapping.terrainmap",
                    ),
                ),
                (
                    "from_sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_paths",
                        to="mapping.terrainsector",
                    ),
                ),
                (
                    "to_sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_paths",
                        to="mapping.terrainsector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terrain Path",
                "verbose_name_plural": "Terrain Paths",
                "ordering": ["terrain_map", "from_sector"],
            },
        ),
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "waypoint_id",
                    models.CharField(
                        help_text="Waypoint identifier (e.g., 'WP1', 'nav-alpha')",
                        max_length=50,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("x_m", models.FloatField(help_text="X coordinate in meters")),
                ("y_m", models.FloatField(help_text="Y coordinate in meters")),
                (
                    "z_m",
                    models.FloatField(help_text="Z coordinate in meters (vertical)"),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        blank=True, help_text="Sequence number in a route", null=True
                    ),
                ),
                (
                    "route_group",
                    models.CharField(
                        blank=True, help_text="Route group identifier", max_length=100
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata (features, notes, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "terrain_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to="mapping.terrainmap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waypoint",
                "verbose_name_plural": "Waypoints",
                "ordering": ["terrain_map", "route_group", "sequence", "waypoint_id"],
                "unique_together": {("terrain_map", "waypoint_id")},
            },
        ),
    ]
