# Generated by Django 6.0.5 on 2026-05-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mapping",
            "0002_digitaltwinsite_mapartifact_terrainmap_terrainsector_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="terrainpath",
            name="path_type",
            field=models.CharField(
                choices=[
                    ("passage", "Passage"),
                    ("climb", "Climb"),
                    ("descent", "Descent"),
                    ("crawl", "Crawl"),
                    ("squeeze", "Tight Squeeze"),
                    ("swim", "Underwater"),
                    ("dive", "Technical Dive"),
                    ("traverse", "Traverse"),
                    ("ladder", "Ladder/Fixed Aid"),
                    ("open", "Open Path"),
                    ("wade", "Wade (Shallow Water)"),
                    ("sealed_passage", "Sealed/Watertight Door"),
                    ("emergency_hatch", "Emergency Hatch"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="terrainsector",
            name="sector_type",
            field=models.CharField(
                choices=[
                    ("chamber", "Chamber"),
                    ("passage", "Passage"),
                    ("junction", "Junction"),
                    ("entrance", "Entrance"),
                    ("shaft", "Vertical Shaft"),
                    ("sump", "Water-filled Sump"),
                    ("room", "Room"),
                    ("corridor", "Corridor"),
                    ("void", "Void Space"),
                    ("hazard", "Hazard Zone"),
                    ("cargo_hold", "Cargo Hold"),
                    ("engine_room", "Engine Room"),
                    ("bridge", "Bridge"),
                    ("crew_quarters", "Crew Quarters"),
                    ("bilge", "Bilge"),
                    ("hull_breach", "Hull Breach"),
                ],
                max_length=50,
            ),
        ),
    ]
