# Generated by Django 6.0.5 on 2026-05-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0003_alter_terrainpath_path_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terrainsector",
            name="sector_type",
            field=models.CharField(
                choices=[
                    ("chamber", "Chamber"),
                    ("passage", "Passage"),
                    ("junction", "Junction"),
                    ("entrance", "Entrance"),
                    ("shaft", "Vertical Shaft"),
                    ("sump", "Water-filled Sump"),
                    ("room", "Room"),
                    ("corridor", "Corridor"),
                    ("void", "Void Space"),
                    ("hazard", "Hazard Zone"),
                    ("cargo_hold", "Cargo Hold"),
                    ("engine_room", "Engine Room"),
                    ("bridge", "Bridge"),
                    ("crew_quarters", "Crew Quarters"),
                    ("bilge", "Bilge"),
                    ("hull_breach", "Hull Breach"),
                    ("utility_corridor", "Utility Corridor"),
                    ("equipment_room", "Equipment Room"),
                    ("pipe_corridor", "Pipe Corridor"),
                    ("tank_chamber", "Tank Chamber"),
                    ("control_room", "Control Room"),
                    ("confined_space", "Confined Space"),
                ],
                max_length=50,
            ),
        ),
    ]
