# Generated by Django 6.0.5 on 2026-05-29 20:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usecases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorPackageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("lidar", "LiDAR"),
                            ("thermal", "Thermal Camera"),
                            ("rgb_camera", "RGB Camera"),
                            ("microphone_array", "Microphone Array"),
                            ("co2_sensor", "CO2 Sensor"),
                            ("gas_sensor", "Gas Sensor"),
                            ("wifi_scanner", "WiFi Scanner"),
                            ("bluetooth_scanner", "Bluetooth Scanner"),
                            ("pressure_sensor", "Pressure Sensor"),
                            ("humidity_sensor", "Humidity Sensor"),
                            ("temperature_sensor", "Temperature Sensor"),
                            ("sonar", "Sonar"),
                            ("imu", "IMU"),
                            ("nfc_module", "NFC Module"),
                            ("water_quality", "Water Quality Sensor"),
                        ],
                        max_length=50,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "data_format",
                    models.CharField(
                        choices=[
                            ("point_cloud", "Point Cloud"),
                            ("image", "Image"),
                            ("video", "Video Stream"),
                            ("audio", "Audio Stream"),
                            ("scalar", "Scalar Value"),
                            ("json", "JSON Data"),
                            ("binary", "Binary Data"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "expected_output",
                    models.TextField(
                        blank=True, help_text="Description of expected sensor output"
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        default=dict,
                        help_text="Sensor specs: range, resolution, frequency, accuracy, etc.",
                    ),
                ),
                (
                    "failure_modes",
                    models.JSONField(
                        default=list,
                        help_text="List of possible failure modes for this sensor",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_packages",
                        to="usecases.agentroletemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor Package Template",
                "verbose_name_plural": "Sensor Package Templates",
                "ordering": ["agent_role", "sensor_type"],
            },
        ),
    ]
