# Generated by Django 6.0.5 on 2026-05-29 20:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UseCaseTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("life_safety", "Life Safety"),
                            ("navigation_safety", "Navigation Safety"),
                            ("infrastructure_safety", "Infrastructure Safety"),
                            ("operational_efficiency", "Operational Efficiency"),
                        ],
                        max_length=50,
                    ),
                ),
                ("summary", models.TextField()),
                ("objective", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_demo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Use Case Template",
                "verbose_name_plural": "Use Case Templates",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="TerrainProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("terrain_type", models.CharField(max_length=200)),
                (
                    "gps_status",
                    models.CharField(
                        choices=[
                            ("denied", "GPS Denied"),
                            ("degraded", "GPS Degraded"),
                            ("intermittent", "GPS Intermittent"),
                            ("available", "GPS Available"),
                        ],
                        max_length=50,
                    ),
                ),
                ("communication_conditions", models.TextField()),
                ("lighting_conditions", models.TextField()),
                (
                    "hazards",
                    models.JSONField(
                        default=list, help_text="List of environmental hazards"
                    ),
                ),
                ("accessibility", models.TextField(blank=True)),
                (
                    "simulation_complexity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        default="medium",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "use_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terrain",
                        to="usecases.usecasetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terrain Profile",
                "verbose_name_plural": "Terrain Profiles",
            },
        ),
        migrations.CreateModel(
            name="AgentRoleTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        help_text="Primary role: scout, relay, mapper, etc.",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("default_quantity", models.PositiveIntegerField(default=1)),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("drone", "Drone"),
                            ("ground_robot", "Ground Robot"),
                            ("amphibious_robot", "Amphibious Robot"),
                            ("relay_node", "Relay Node"),
                            ("sensor", "Passive Sensor"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        default=list,
                        help_text="List of capabilities: mapping, relay, thermal_sensing, etc.",
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        default=dict,
                        help_text="Hardware specs: battery_capacity, max_speed, sensor_range, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "use_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_roles",
                        to="usecases.usecasetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Role Template",
                "verbose_name_plural": "Agent Role Templates",
                "ordering": ["use_case", "name"],
            },
        ),
    ]
